import os
IMG_FILE = os.path.join("..", "img")
DATA_FOLDER = os.path.join("..", "data")
SMART_BETA_TICKERS = ["VTV", "VUG", "IWF", "VIG" ,"IWD", "VYM", "SCHD", "RSP", "IVW", "USMV"]
OVERALL_ESG_TICKERS = ["ESGV", "ESGE", "XVV", "VSGX", "SUSB"]
ENVIRONMENT_ESG_TICKERS = ["ICLN", "CNRG", "CRBN", "SPYX", "ERTH"]
SOCIAL_ESG_TICKERS = ["DSI", "SUSA", "NUEM", "ICAN", "SHE"]
INDEX_TRACKER_TICKERS = ["SPY", "IWM", "QQQ", "IVV", "DIA", "VTI",]
SMART_BETA_ESG_TICKERS = ["RSPE", "MVEE.SW", "RAFE"]

HEALTHY_TICKERS = ["XHE", "PSCC", "BMED", "PBE", "FXH", "HTEC", "PINK", "IHI", "CHIH", "XBI"]
HEALTHY_SB_TICKETS = ["EUSC","JHMH", "GXTG", "XLV", "SPMV", "PTH", "LVHI", "RODM", "IEIH", "BTEC"]
CARBON_THEME_TICKERS = ["SDG","ERTH", "KGRN", "WNDY", "GBLD", "FRNW", "TAN", "ACES", "RNRG", "ICLN"]
CARBON_THEME_SB_TICKERS = ["SOLR", "EWRE", "RYH", "RHS", "IDHD", "UTRN", "MID", "AMOM", "JHMH", "ESMV"]
WATER_CLEAN_ENERGY_TICKERS = ["RNRG", "QCLN", "WOOD", "CTEX", "CLMA", "DTOX", "SHFT", "CNRG", "AQWA", "CGW"]
WATER_CLEAN_ENERGY_SB_TICKERS = ["STNC", "NULG", "MXDU", "EWJE", "ADIV", "JPIN", "IDLV", "IMFL", "PUI", "FEDM"]